### ISSUE TITLE
Program sink doesn't writes to stdin?

### ISSUE THREAD

**Issue by raphaelyancey** [dshearer/jobber-docker#6]
Hi, I'm having an issue reading `stdin` in a program sink.

`/home/jobber/.jobber`
```yaml
version: 1.4
jobs:
  GroupDefine:
    cmd: curl -v http://app/script.php
    time: 0 * * * * *
    onError: Backoff
    notifyOnSuccess:
      - type: program
        path: /usr/local/bin/barbaz
```
`/usr/local/bin/barbaz`
```bash
#!/bin/bash
echo < /dev/stdin > /tmp/stdout.txt
# Also tried with <&0 instead of < /dev/stdin
```

```bash
$ docker-compose exec jobber cat /tmp/stdout.txt

$ # ^ file is created but is empty
```

`/tmp/stdout.txt` should be filled with a `RecRecording`, right?
